In [ ]:
import numpy as np
import matplotlib.pyplot as plt

def initialise_grid(N, n):
    x = np.zeros((N, N))
    k = 0
    while k < n:
        i = np.random.randint(N)
        j = np.random.randint(N)
        if x[i,j] == 0:
            k += 1
            x[i,j] = 1
    k = 0
    while k < n:
        i = np.random.randint(N)
        j = np.random.randint(N)
        if x[i,j] == 0:
            k += 1
            x[i,j] = 2
    
    return x

def neighbours_same(x, i, j):
    N = len(x)
    count = 0
    for a in range(max((i-1), 0), min(i+2, N)):
        for b in range(max((j-1), 0), min(j+2, N)):
            if x[a, b] == x[i,j]:
                count = count + 1
    count = count - 1
    return count

def neighbours_total(x, i, j):
    N = len(x)
    count = 0
    for a in range(max((i-1), 0), min(i+2, N)):
        for b in range(max((j-1), 0), min(j+2, N)):
            if x[a, b] != 0:
                count = count + 1
    if x[i, j] != 0:
        count = count - 1
    return count

def get_dissatisfied_cells(x, f):
    N = len(x)
    dis = np.zeros((N, N))
    for i in range(N):
        for j in range(N):
            same = neighbours_same(x, i, j)
            total = neighbours_total(x, i, j)
            if x[i,j] != 0 and total != 0 and same/total < f:
                dis[i,j] = 1
    return dis
            
def advance(x, f):
    N = len(x)
    dis = get_dissatisfied_cells(x, f)
    result = np.zeros((N, N))
    for i in range(N):
        for j in range(N):
            if dis[i, j] == 0:
                result[i, j] = x[i, j]
                
    for i in range(N):
        for j in range(N):
            if dis[i, j] == 1:
                i_new = np.random.randint(N)
                j_new = np.random.randint(N)
                while result[i_new, j_new] != 0:
                    i_new = np.random.randint(N)
                    j_new = np.random.randint(N)
                result[i_new, j_new] = x[i, j]
    return result

N = 15
n = 100
f = 0.5

grid = initialise_grid(N, n)

plt.figure()
plt.imshow(grid)

for i in range(10):
    
    grid = advance(grid, f)
    plt.figure()
    plt.imshow(grid)



: 

# NSCI0007 Coursework (LSA)

## Background

Suppose there are two species of organism which live in a neighbourhood consisting of a square grid of cells. Populations of the two species are initially placed into random locations of a neighbourhood represented by a grid. After placing all the organisms in the grid, each cell is either occupied by an organism or is empty as shown below.

![](grid1.png)

The organisms prefer to be surrounded by organisms of the same type. An organism is *satisfied* if it is surrounded by at least a fraction $f$ of organisms that are of a like species.

For example, if $f = 0.3$, an organism is satisfied if at least 30% of its neighbours are the same species as itself. If the organism is satisfied, then it will remain in its current location. If fewer than 30% are the same species, then the organism is not satisfied, and it will want to change its location in the grid.

The picture below (left) shows a satisfied organism because 50% of X's neighbors are also X ($50\% > f$). The next X (right) is not satisfied because only 25% of its neighbors are X ($25\% < f$). Notice that empty cells are not counted when calculating similarity.

![](grid2.png) ![](grid3.png)

When an organism is not satisfied, it is moved to any vacant location in the grid. The new location is chosen at random from amongst the empty cells.

In the image below (left), all dissatisfied organisms have an asterisk next to them. The image on the right shows the new configuration after all the dissatisfied organisms have been moved to unoccupied cells at random. Note that the new configuration may cause some organisms which were previously satisfied to become dissatisfied!

![](grid4.png) ![](grid5.png)

All dissatisfied organisms are moved in the same round. After the round is complete, a new round begins, and dissatisfied organisms are once again moved to new locations in the grid. These rounds continue until all organisms in the neighbourhood are satisfied with their location.

The animation below shows an example of how the distribution of two populations might evolve. Notice that the distribution eventually settles down to a stable pattern with organisms segregated into distinct regions.

```{image} atlas.gif
:width: 300px
:align: center
```

## Coursework

By following the steps below you will implement the simulation using Python. You will model the grid as an array containing the values `1` and `2` which represent the two species of organism and `0` which represents an empty cell. Starter code is provided to help you.


First you will write a function which places `n` `1`s and `n` `2`s at random locations in an `N` by `N` array.

The following code uses the function `randint` to place `1` at a random location in a `3` by `3` array `x` six times:
```
import numpy as np

x = np.zeros((3, 3))

for n in range(6):
    i = np.random.randint(3)
    j = np.random.randint(3)
    x[i, j] = 1
        
print(x)
```

Notice that when you run the code, we don't end up with six ones! This is because we sometimes end up randomly choosing the same cell twice.

You can fix this problem by replacing the `for` loop with a `while` loop which terminates once we have placed six `1`s in to empty cells.

### Question 1 [5 marks] 

Write a function `initialise_grid(N, n)` which returns an array of dimensions `N` by `N` containing exactly `n` `1`s and `n` `2`s placed at random cells in the array. Use the code below to help.

```
def initialise_grid(N, n):
    x = np.zeros((N, N))
    k = 0
    while k < n:
        # select a random i and j
        # if the cell i, j is empty, set it to 1 and increase k
    
    # same again for 2s
    
    return x
```

Test that your code works as below.

In [ ]:
grid = initialise_grid(4, 5)

# A 4 by 4 array with exactly 5 `1`s and 5 `2`s
print(grid)

: 


The function `neighbours_same(x, i, j) ` returns the number of neighbours which are of the same species as cell `i, j`. Notice the carefully calculated limits of the for loop so that we don't go beyond the borders of the grid!

```
def neighbours_same(x, i, j):
    N = len(x)
    count = 0
    for a in range(max((i-1), 0), min(i+2, N)):
        for b in range(max((j-1), 0), min(j+2, N)):
            if x[a, b] == x[i,j]:
                count = count + 1
    count = count - 1 # subtract 1 since the cell i, j always equals itself!
    return count
```

### Question 2 [5 marks]

Write a function `neighbours_total(x, i, j)` which returns the total number of non-empty neighbouring cells of cell `i, j`. Check that your function works in the following cases:

In [3]:
x = np.array([[2, 2, 1, 2, 1],
              [0, 1, 1, 1, 1],
              [2, 2, 0, 0, 0],
              [2, 1, 2, 2, 2],
              [2, 1, 1, 0, 1]])

            
print(neighbours_total(x, 0, 0)) # should print 2
print(neighbours_total(x, 0, 1)) # should print 4
print(neighbours_total(x, 1, 0)) # should print 5
print(neighbours_total(x, 1, 1)) # should print 6

2
4
5
6


### Question 3 [10 marks]

Write a function `get_dissatisfied_cells(x, f)` which returns an `N` by `N` array whose values are `1` for cells containing a dissatisfied organism, or `0` otherwise. An organism is disatisfied if the fraction of its neighbours which are the same as it is less than `f`.

```
def get_dissatisfied_cells(x, f):
    N = len(x)
    dis = np.zeros((N, N))
    
    # loop over all cells in x
    # and determine if it is satisfied

    return dis
```

For example,

In [4]:
x = np.array([[2, 2, 1, 2, 1],
              [0, 1, 1, 1, 1],
              [2, 2, 0, 0, 0],
              [2, 1, 2, 2, 2],
              [2, 1, 1, 0, 1]])
f = 0.4

print(get_dissatisfied_cells(x, f))

[[0. 1. 0. 1. 0.]
 [1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 1. 1.]]


### Question 4 [10 marks]

Write a function `advance(x, f)` which returns the array of cells after moving all dissatisfied organisms to an unoccupied cell.

You will need to do this in two steps:

1. **Satisfied organisms stay where they are:** loop over all cells in `dis`, and for each satisfied cell set the value of `result` to the same value as the equivalent cell in `x`.
2. **Dissatisfied organisms move to a random empty cell:** loop over all cells again. For each unsatisfied cell, choose a random empty cell and set its value to the species number. As in Question 1, you can use a while loop to find a random empty cell.

```
def advance(x, f):
    N = len(x)
    dis = get_dissatisfied_cells(x, f)
    result = np.zeros((N, N))
    
    # loop over all cells in dis
    # and set value of result if satisfied
                
    # loop over all cells in dis
    # for each disatisfied cell, find a random
    # empty cell in result and set its value
```

Check your code works similarly to below.

In [5]:
x = np.array([[2, 2, 1, 2, 1],
              [0, 1, 1, 1, 1],
              [2, 2, 0, 0, 0],
              [2, 1, 2, 2, 2],
              [2, 1, 1, 0, 1]])
f = 0.3

x2 = advance(x, f)
print(x2)

[[2. 2. 1. 2. 1.]
 [0. 1. 1. 1. 1.]
 [2. 2. 0. 1. 0.]
 [2. 0. 2. 2. 2.]
 [2. 1. 1. 1. 0.]]


### Question 5 [10 marks]

Initialise the grid to an `15` by `15` array with 10% unoccupied. Run the simulation for `10` iterations with `f = 0.4` and display the contents of the array at each step using `matplotlib.pyplot.imshow`.

Experiment with different values of `f`. For what values of `f` does the grid eventually reach a stable pattern?

```
import numpy as np
import matplotlib.pyplot as plt

N = 15
n = 100
f = 0.5

grid = initialise_grid(N, n)

plt.figure()
plt.imshow(grid)

# Your code goes here
```