# Tutorial 5: Cellular Automata

A cellular automaton is a collection of cells on a rectangular grid that evolves through a number of discrete time steps according to a set of rules based on the states of neighbouring cells. The rules are then applied iteratively for as many time steps as desired.

You will investigate a cellular automaton model as part of your group project.

```{figure} epidemic.png
---
height: 200px
name: epidemic-fig
---
Cellular automata models of the spread of an epidemic on a 2-dimensional grid of cells. Each timestep corresponds to one day {footcite}`gagliardi2010small`.
```

## Conway's Game of Life

The **Game of Life** is a simple cellular automaton devised by mathematician John Conway in 1970. The automaton mimics the dynamical evolution of "life-forms" existing in the grid of cells {numref}`game-of-life-fig` shows an example evolution of the Game of Life for two iterations.

```{admonition} The Rules of Conway's Game of Life

1. Start with a rectangular grid of cells, each of which is "alive" (black) or "dead" (white).
2. Count the number of each cell’s 8 immediate neighbours that are alive, and  
  a. any live cell with fewer than 2 live neighbours dies;  
  b. any live cell with more than 3 live neighbours dies;  
  c. any live cell with 2 or 3 live neighbours lives on;  
  d. any dead cell with exactly three live neighbours becomes alive, and otherwise stays dead.
3. Repeat step 2 as many times as desired.

```

```{figure} game_of_life_example.png
---
height: 150px
name: game-of-life-fig
---
Two iterations of the Game of Life on a 5 by 5 grid.
```

The remainder of this workshop involves constructing code to execute the Game of Life


```{exercise}
What would the next iteration of the Game of Life in {numref}`game-of-life-fig` look like?

Using pseudocode, sketch an algorithm for calculating one iteration of the Game of Life.
```


## Programming the Game of Life

Below is template code for a Python program which executes a single iteration of the game of life. The first function `count_neighbours` calculates the number of live neighbours of single cell, whereas the function `advance` calculates the next iteration of the entire grid of cells.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

def count_neighbours(grid, i, j):
    pass
    # Return the number of live neighbours
    # of the cell at position i, j

def advance(grid):
    n, m = grid.shape
    new_grid = np.zeros((n,m))
    
    # Loop over each of the cells in the grid.
    # For each cell, determine the number of live neighbours.
    # Use the game of life rules to determine if the cell lives or dies.
    # Finally, set the value of the equivalent cell in new_grid

    return new_grid

n = 5
grid1 = np.zeros((n, n))

# set the initial value of grid1

print("grid1:")
print(grid1)

grid2 = advance(grid1)

print("grid2:")
print(grid2)



grid1:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
grid2:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


:::{exercise}

Complete the function `count_neighbours(grid, i, j)` so that it returns the total number of live neighbours of cell `i`, `j`.

**Hint:** for cells that aren't on one of the edges, the following code will calculate the total number of neighours in the 3 by 3 grid of cells centred at `i`, `j`:

```
sum(grid[i-1:i+2, j-1:j+2])
```

You will need to adapt this code for 
:::

In this question, you will write code which implements Conway's Game of Life on an $n$ by $n$ grid. Template code is given below - copy and paste this into a new notebook then replace the comments with your own code to get this working.

NB `pass` is Python keyword which means 'do nothing'. You will also need to delete this!

Once you have got your code working, test it out with some of the patterns here.

Hints

 - First get `count_neighbours` working and test it on specific cells
 - if you're struggling to get the full Game of Life rules working, first try a 'simplified' version. E.g a cell is alive in the next step if *any* of its neighbours is alive in the current step


## Question 2

Get this working on a 3-d `n` by `n` by `t` array where `t` is the number of time steps.

Generate embedded video


## Question 3

You'll have noticed that some starting patterns quickly die out, whereas some spawn a complicted series of activity which lasts a long time. To invesitage this, we'd like to generate a line graph which shows the total number of active cells at each timestep.

Write a function `activity_graph(grid)` which plots a line graph as shown.

## Question 4

Some starting patterns eventually settle down to an oscillating between states. Write a function which returns the number of states in the cycle.

`def cycle_period(grid):`

## Question 5

Some starting patterns 'gliders' oscillate between states, but shifted by a cell in some direction. Write a function which idenfities if a starting pattern is a glider.

`def is_glider(grid):`


```{footbibliography}
```