# Tutorial 5: Cellular Automata

TODO: Introduction to Cellular Automata

The Rules of the Game
1. Start with a square grid of “cells”, each of which is “alive” (black) or “dead” (white).
2. At each step, we count the number of each cell’s 8 immediate neighbours that are alive, and  
  a. any live cell with fewer than 2 live neighbours dies  
  b. any live cell with more than 3 live neighbours dies  
  c. any live cell with 2 or 3 live neighbours lives on  
  d. any dead cell with exactly three live neighbours becomes alive, and otherwise stays dead



![](game_of_life_example.png)

## Question 1




In this question, you will write code which implements Conway's Game of Life on an $n$ by $n$ grid. Template code is given below - copy and paste this into a new notebook then replace the comments with your own code to get this working.

NB `pass` is Python keyword which means 'do nothing'. You will also need to delete this!

Once you have got your code working, test it out with some of the patterns here.

Hints

 - First get `count_neighbours` working and test it on specific cells
 - if you're struggling to get the full Game of Life rules working, first try a 'simplified' version. E.g a cell is alive in the next step if *any* of its neighbours is alive in the current step


In [9]:
import numpy as np
import matplotlib.pyplot as plt

def count_neighbours(grid, i, j):
    pass
    # Return the number of live neighbours
    # of the cell at position i, j

def advance(grid):
    n, m = grid.shape
    new_grid = np.zeros((n,m))
    
    # Loop over each of the cells in the grid.
    # For each cell, determine the number of live neighbours.
    # Use the game of life rules to determine if the cell lives or dies.
    # Finally, set the value of the equivalent cell in new_grid

    return new_grid

n = 5
grid1 = np.zeros((n, n))

# set the initial value of grid1

print("grid1:")
print(grid1)

grid2 = advance(grid1)

print("grid2:")
print(grid2)



grid1:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
grid2:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## Question 2

Get this working on a 3-d `n` by `n` by `t` array where `t` is the number of time steps.

Generate embedded video


## Question 3

You'll have noticed that some starting patterns quickly die out, whereas some spawn a complicted series of activity which lasts a long time. To invesitage this, we'd like to generate a line graph which shows the total number of active cells at each timestep.

Write a function `activity_graph(grid)` which plots a line graph as shown.

## Question 4

Some starting patterns eventually settle down to an oscillating between states. Write a function which returns the number of states in the cycle.

`def cycle_period(grid):`

## Question 5

Some starting patterns 'gliders' oscillate between states, but shifted by a cell in some direction. Write a function which idenfities if a starting pattern is a glider.

`def is_glider(grid):`